apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-viki
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-bpzd-tenant/rhtap-demo-app/hacbs-test-project-viki@sha256:9c4b8e6f3e25d22a1a60d7993a7f00d365ef947cf71819b1ff854c228d0157b2
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
