apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-viki
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-viki
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-viki
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-viki
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-viki
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-bpzd-tenant/rhtap-demo-app/hacbs-test-project-viki@sha256:9840954948ee791b88d781014f22f0da202ee343015316dc3e0c569cfe908e0f
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
